{% set version = "0.0.6" %}

package:
  name: blackbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blackbook/blackbook-{{ version }}.tar.gz
  sha256: ab6370333e0b1f3791f90b4d275944b839082a6e4d6ec7bfd66bce234a8eb1df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - blackbook=blackbook.__main__:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - black >=18.9b0
    - loguru >=0.2.5

test:
  imports:
    - blackbook
  commands:
    - blackbook .

about:
  home: The package home page
  license: The MIT (MIT)
  license_family: MIT
  license_file: LICENSE
  summary: Black for Jupyter notebooks

extra:
  recipe-maintainers:
    - ocefpaf
