{% set version = "0.0.5" %}

package:
  name: blackbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blackbook/blackbook-{{ version }}.tar.gz
  sha256: 7a2bd83efd88c1835791056bc36ed2e83c07373846e2f75837a2272b6460355c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - blackbook=blackbook.__main__:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - black >=18.9b0
    - loguru >=0.2.5

test:
  imports:
    - blackbook
  commands:
    - blackbook --help

about:
  home: The package home page
  license: The MIT (MIT)
  license_family: MIT
  license_file: LICENSE
  summary: Black for Jupyter notebooks

extra:
  recipe-maintainers:
    - ocefpaf
